; Enable opcache and configure for Laravel
opcache.enable_cli=1
opcache.enable=1
opcache.memory_consumption=192
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=10000
opcache.revalidate_freq=0
opcache.validate_timestamps=1
opcache.max_wasted_percentage=10

; Security tweaks
expose_php=Off
disable_functions=shell_exec,system

; File size settings
upload_max_filesize=25M
post_max_size=25M

; Memory limit
memory_limit=1G

; Execution time
max_execution_time=180

; Needed until tenancy backport is removed
error_reporting=E_ALL & ~E_DEPRECATED & ~E_STRICT
display_errors=Off
