image: node:14.15

stages:
  - build
  - deploy

build_frontend:
  image: node:14.15
  stage: build
  only:
    - master
  artifacts:
    expire_in: 1 week
    paths:
      - dist
  script:
    - 'echo "//gitlab.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}" > ~/.npmrc'
    - npm config set @kibro:registry https://gitlab.com/api/v4/packages/npm/
    - npm install
    - npm run build

build_backend:
  image: registry.gitlab.com/kibro/brezel/api
  stage: build
  only:
    - master
  artifacts:
    expire_in: 1 week
    paths:
      - vendor
  before_script:
    - composer config repositories.10031718 composer https://__token__:$PACKAGE_REGISTRY_TOKEN@gitlab.com/api/v4/group/10031718/-/packages/composer/packages.json
  script:
    - composer install

deploy_frontend:
  image: docker:git
  stage: deploy
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  only:
    - master
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker info
    - docker pull $CI_REGISTRY_IMAGE:static || true
    - docker build -f static.Dockerfile --cache-from $CI_REGISTRY_IMAGE:static --tag $CI_REGISTRY_IMAGE:static-$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:static .
    - docker push $CI_REGISTRY_IMAGE:static-$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:static
