# Use mise (mise-en-place) to define what is needed to run brezel.
# If properly configured, this will cause your terminal to use the correct versions of tools when in this project dir.
# Also provides helpful tasks to automate common commands.

# Required system tools
[tools]
bun = "latest"
zellij = "latest"

# Quick aliases to run common tasks. Note: requires mise 2025.12.11 and up!
[shell_alias]
u = "mise run update"
a = "mise run apply"
l = "mise run load"
brezel = "./bin/brezel" # Run a php command such as `php bakery apply` in the containers with `brezel bakery apply`

# Tasks
[tasks.composer-install]
description = "Install composer dependencies"
run = "bin/compose run --rm deps"

[tasks.npm-install]
description = "Install npm dependencies"
run = "bin/compose run --rm node_deps"

[tasks.install]
description = "Install all dependencies"
depends = [
    "composer-install",
    "npm-install"
]

[tasks.composer-update]
description = "Do a composer update"
run = "bin/compose run --rm deps composer update"

[tasks.init]
description = "Initialize the project"
run = "bin/brezel bakery init"

[tasks.apply]
description = "Do a bakery apply"
run = "bin/brezel apply"

[tasks.load]
description = "Reload Workflows"
run = "bin/brezel load"

[tasks.update]
description = "Update the systems (Spec, Worklows, etc)"
run = "bin/brezel update"

[tasks.serve]
description = "Start the Docker stack in Zellij and stop it again when the session ends"
run = "bin/brezel serve"
